/*******************************************************************************
 * Copyright 2017 Xoriant Corporation.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
/*
 * Doctor Appointment
 * Appointment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Doctor
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-22T11:51:09.190Z")
public class Doctor {
  @SerializedName("doctorId")
  private Long doctorId = null;

  @SerializedName("doctorName")
  private String doctorName = null;

  @SerializedName("visitingCharge")
  private Long visitingCharge = null;

  @SerializedName("availability")
  private Long availability = null;

  @SerializedName("speciality")
  private String speciality = null;

  public Doctor doctorId(Long doctorId) {
    this.doctorId = doctorId;
    return this;
  }

   /**
   * Get doctorId
   * @return doctorId
  **/
  @ApiModelProperty(value = "")
  public Long getDoctorId() {
    return doctorId;
  }

  public void setDoctorId(Long doctorId) {
    this.doctorId = doctorId;
  }

  public Doctor doctorName(String doctorName) {
    this.doctorName = doctorName;
    return this;
  }

   /**
   * Get doctorName
   * @return doctorName
  **/
  @ApiModelProperty(value = "")
  public String getDoctorName() {
    return doctorName;
  }

  public void setDoctorName(String doctorName) {
    this.doctorName = doctorName;
  }

  public Doctor visitingCharge(Long visitingCharge) {
    this.visitingCharge = visitingCharge;
    return this;
  }

   /**
   * Get visitingCharge
   * @return visitingCharge
  **/
  @ApiModelProperty(value = "")
  public Long getVisitingCharge() {
    return visitingCharge;
  }

  public void setVisitingCharge(Long visitingCharge) {
    this.visitingCharge = visitingCharge;
  }

  public Doctor availability(Long availability) {
    this.availability = availability;
    return this;
  }

   /**
   * Get availability
   * @return availability
  **/
  @ApiModelProperty(value = "")
  public Long getAvailability() {
    return availability;
  }

  public void setAvailability(Long availability) {
    this.availability = availability;
  }

  public Doctor speciality(String speciality) {
    this.speciality = speciality;
    return this;
  }

   /**
   * Get speciality
   * @return speciality
  **/
  @ApiModelProperty(value = "")
  public String getSpeciality() {
    return speciality;
  }

  public void setSpeciality(String speciality) {
    this.speciality = speciality;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Doctor doctor = (Doctor) o;
    return Objects.equals(this.doctorId, doctor.doctorId) &&
        Objects.equals(this.doctorName, doctor.doctorName) &&
        Objects.equals(this.visitingCharge, doctor.visitingCharge) &&
        Objects.equals(this.availability, doctor.availability) &&
        Objects.equals(this.speciality, doctor.speciality);
  }

  @Override
  public int hashCode() {
    return Objects.hash(doctorId, doctorName, visitingCharge, availability, speciality);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Doctor {\n");
    
    sb.append("    doctorId: ").append(toIndentedString(doctorId)).append("\n");
    sb.append("    doctorName: ").append(toIndentedString(doctorName)).append("\n");
    sb.append("    visitingCharge: ").append(toIndentedString(visitingCharge)).append("\n");
    sb.append("    availability: ").append(toIndentedString(availability)).append("\n");
    sb.append("    speciality: ").append(toIndentedString(speciality)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

