/*******************************************************************************
 * Copyright 2017 Xoriant Corporation.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
/*
 * Doctor Appointment
 * Appointment
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2001;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SlotsApi
 */
@Ignore
public class SlotsApiTest {

    private final SlotsApi api = new SlotsApi();

    
    /**
     * Deletes Slots for an Id
     *
     * delete operation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSlotsByIdTest() throws ApiException {
        Long slotId = null;
        api.deleteSlotsById(slotId);

        // TODO: test validations
    }
    
    /**
     * Find Slots by slotId
     *
     * Get Slots for specified slotId
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSlotsBySlotIdTest() throws ApiException {
        List<String> slotId = null;
        List<InlineResponse2001> response = api.getSlotsBySlotId(slotId);

        // TODO: test validations
    }
    
    /**
     * Updates a Slot with form data
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSlotsForDoctorIdTest() throws ApiException {
        Long slotId = null;
        Long doctorId = null;
        api.updateSlotsForDoctorId(slotId, doctorId);

        // TODO: test validations
    }
    
}
